# conda env create -f environment.yml
# mamba env create -f environment.yml
# micromamba env create -f environment.yml

name: docking-2024

channels:
  - defaults
  - schrodinger
  - conda-forge


dependencies:
  - smina
  - python
  - openbabel
  - rdkit
  - notebook
  - ipykernel
  - ipython
  - nb_conda_kernels
  - plotly
  - tqdm
  - seaborn
  - scikit-learn
  - pymol-bundle
  - statsmodels
  - pip
  - pip:
    - molplotly
